"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import myApp

# Implementing MyFrame1
class MyProject1MyFrame1( myApp.MyFrame1 ):
	def __init__( self, parent ):
		myApp.MyFrame1.__init__( self, parent )

